<?php
namespace FuriosoJack\KaseyaSDKSOAP\Tests;
use Dotenv\Dotenv;

/**
 * Class TestCase
 * @author Juan Diaz - FuriosoJack <iam@furiosojack.com>
 */
class TestCase extends \PHPUnit\Framework\TestCase
{

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $dotenv = new Dotenv(__DIR__);
        $dotenv->load();

    }

}